Resources:
  dogCollarTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${self:service}-${self:provider.stage}-snsTopic
  smartDogCollarBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${self:service}-${self:provider.stage}
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
  smartDogCollarBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub ${self:service}-${self:provider.stage}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "PublicReadGetObject"
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub arn:aws:s3:::!Sub ${self:service}-${self:provider.stage}/*