Resources:
  collarQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "smart-dog-collar-app-test-collarQueue"
      ReceiveMessageWaitTimeSeconds: 10
      VisibilityTimeout: 90
  collarLoggerQueueFIFO:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "smart-dog-collar-app-test-collarLoggerQueue.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true
  dogCollarTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "smart-dog-collar-app-test-snsTopic"
  smartDogCollarBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: smart-dog-collar-test
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
  smartDogCollarBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: smart-dog-collar2
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "PublicReadGetObject"
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::smart-dog-collar2/*"